# Commands that should be blocked from tab.
commands:
  - ver
  - version
  - about
  - bukkit
  - icanhasbukkit
  - help
  - '?'
  - me
  - minecraft:me
  - minecraft:help
  - bukkit:?
  - bukkit:help
  - plugins
  - pl
  - bukkit:pl
  - bukkit:plugins
  - bukkit:ver
  - bukkit:version
  - bukkit:about
  - pl-hide:plhide
  - plhide
  - cmi
  - cback
  - vault-info
  - vault-convert
  - br
  - brush
  - desel
  - deselect
  - sel
  - toggleplace
  - /br
  - /brush
  - /desel
  - /deselect
  - /sel
  - /toggleplace
  - ;
  - mv
  - mvc
  - mvco
  - mvclone
  - mvconfirm
  - mvcoord
  - mvcreate
  - mvdebug
  - mvdelete
  - mvenv
  - mvgamerule
  - mvgamerules
  - mvgenerators
  - mvgens
  - mvh
  - mvhelp
  - mvi
  - mvim
  - mvimport
  - mvinfo
  - mvl
  - mvlist
  - mvload
  - mvm
  - mvmadd
  - mvmclear
  - mvmodify
  - mvmremove
  - mvmset
  - mvpurge
  - mvr
  - mvregen
  - mvreload
  - mvremove
  - mvrule
  - mvrules
  - mvs
  - mvscript
  - mvsearch
  - mvset
  - mvsetspawn
  - mvsilent
  - mvspawn
  - mvss
  - mvtp
  - mvunload
  - mvv
  - mvversion
  - mvw
  - mvwho
  - rc
  - resadmin
  - resload
  - resreload
  - ta
  - teammsg
  - tell
  - tm
  - tool
  - towny
  - townyadmin
  - townyworld
  - trigger
  - tw
  - w
  - we
  - worldedit
